version: '3.7'

services:
  bot:
    build:
      context: .
    restart: on-failure
    stop_signal: SIGINT
    depends_on:
      - redis
    env_file:
      - ".env"

  redis:
    image: redis:5-alpine
    restart: on-failure
    env_file:
      - ".env"
    volumes:
      - redis-data:/data


volumes:
  redis-data:
